Fix build warnings
clang 3.4 says error: 'register' storage class specifier is deprecated
[-Werror,-Wdeprecated-register], and it's right.

It also says that src/Imap/Parser/3rdparty/rfccodecs.cpp:58:19: error:
unused variable 'especials' [-Werror,-Wunused-const-variable], and it
happens to be right in this case, too.

Change-Id: I67b04db1a3251c8a123c5b1aaafb7b4fed84c408